ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS agent_id BIGINT NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS agent_version VARCHAR(50) NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS device_name VARCHAR(255) NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS collector VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS event_id VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS sequence BIGINT NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS batch_id VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities ADD COLUMN IF NOT EXISTS source_platform VARCHAR(50) NULL;

CREATE INDEX IF NOT EXISTS idx_activities_user_id ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_agent_id ON activities(agent_id);
CREATE INDEX IF NOT EXISTS idx_activities_event_id ON activities(event_id);
CREATE INDEX IF NOT EXISTS idx_activities_batch_id ON activities(batch_id);

ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS user_id BIGINT NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS agent_id BIGINT NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS agent_version VARCHAR(50) NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS device_name VARCHAR(255) NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS collector VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS event_id VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS sequence BIGINT NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS batch_id VARCHAR(100) NULL;
ALTER TABLE IF EXISTS activities_archive ADD COLUMN IF NOT EXISTS source_platform VARCHAR(50) NULL;
