global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/backend-alerts.yml

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: activityservice
    metrics_path: /metrics
    static_configs:
      - targets: ["activityservice:5002"]

  - job_name: authservice
    metrics_path: /metrics
    static_configs:
      - targets: ["authservice:5007"]

  - job_name: userservice
    metrics_path: /metrics
    static_configs:
      - targets: ["userservice:5005"]

  - job_name: metricservice
    metrics_path: /metrics
    static_configs:
      - targets: ["metricservice:5011"]

  - job_name: notificationservice
    metrics_path: /metrics
    static_configs:
      - targets: ["notificationservice:5017"]

  - job_name: reportservice
    metrics_path: /metrics
    static_configs:
      - targets: ["reportservice:5014"]

  - job_name: agentmanagementservice
    metrics_path: /metrics
    static_configs:
      - targets: ["agentmanagementservice:5016"]

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
