#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "$ROOT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/src/endpoint_agent/generated"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "$PYTHON_BIN" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="python"
  else
    echo "Python interpreter not found (expected python3 or python)" >&2
    exit 1
  fi
fi

mkdir -p "$OUT_DIR"

"$PYTHON_BIN" -m grpc_tools.protoc \
  -I "$REPO_DIR/Backend/services/ActivityService/Protos" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$REPO_DIR/Backend/services/ActivityService/Protos/Activity.proto"

"$PYTHON_BIN" -m grpc_tools.protoc \
  -I "$REPO_DIR/Backend/services/AgentManagementService/Protos" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$REPO_DIR/Backend/services/AgentManagementService/Protos/agent.proto"

# Fix imports generated by grpc_tools to package-relative form.
OUT_DIR_PY="$OUT_DIR" "$PYTHON_BIN" - <<'PY'
from pathlib import Path
import os
out = Path(os.environ["OUT_DIR_PY"])

for p in out.glob("*_pb2_grpc.py"):
    text = p.read_text(encoding="utf-8")
    # grpc_tools generates absolute imports that break package-local imports.
    # Normalize to explicit relative imports for all generated modules.
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("import ") and "_pb2 as " in stripped:
            prefix, alias = stripped.split(" as ", 1)
            module = prefix.replace("import ", "", 1)
            line = line.replace(prefix, f"from . import {module}")
        lines.append(line)
    text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    p.write_text(text, encoding="utf-8")
PY

echo "Generated Python gRPC stubs in $OUT_DIR"
