#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "$ROOT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/src/endpoint_agent/generated"

mkdir -p "$OUT_DIR"

python -m grpc_tools.protoc \
  -I "$REPO_DIR/Backend/services/ActivityService/Protos" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$REPO_DIR/Backend/services/ActivityService/Protos/Activity.proto"

python -m grpc_tools.protoc \
  -I "$REPO_DIR/Backend/services/AgentManagementService/Protos" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$REPO_DIR/Backend/services/AgentManagementService/Protos/agent.proto"

# Normalize filenames to lower_case imports expected by Python code.
if [[ -f "$OUT_DIR/Activity_pb2.py" ]]; then mv "$OUT_DIR/Activity_pb2.py" "$OUT_DIR/activity_pb2.py"; fi
if [[ -f "$OUT_DIR/Activity_pb2_grpc.py" ]]; then mv "$OUT_DIR/Activity_pb2_grpc.py" "$OUT_DIR/activity_pb2_grpc.py"; fi
if [[ -f "$OUT_DIR/agent_pb2.py" ]]; then :; fi
if [[ -f "$OUT_DIR/agent_pb2_grpc.py" ]]; then :; fi

# Fix imports generated by grpc_tools after renaming
OUT_DIR_PY="$OUT_DIR" python - <<'PY'
from pathlib import Path
import os
out = Path(os.environ["OUT_DIR_PY"])
for p in out.glob("*_pb2_grpc.py"):
    text = p.read_text(encoding="utf-8")
    text = text.replace("import Activity_pb2 as Activity__pb2", "import activity_pb2 as Activity__pb2")
    p.write_text(text, encoding="utf-8")
PY

echo "Generated Python gRPC stubs in $OUT_DIR"
