# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import activity_pb2 as activity__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in activity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActivityGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActivities = channel.unary_unary(
                '/activity.ActivityGrpcService/GetActivities',
                request_serializer=activity__pb2.GetActivitiesRequest.SerializeToString,
                response_deserializer=activity__pb2.GetActivitiesReply.FromString,
                _registered_method=True)
        self.CreateActivity = channel.unary_unary(
                '/activity.ActivityGrpcService/CreateActivity',
                request_serializer=activity__pb2.CreateActivityRequest.SerializeToString,
                response_deserializer=activity__pb2.ActivityReply.FromString,
                _registered_method=True)
        self.GetActivityById = channel.unary_unary(
                '/activity.ActivityGrpcService/GetActivityById',
                request_serializer=activity__pb2.GetActivityByIdRequest.SerializeToString,
                response_deserializer=activity__pb2.ActivityReply.FromString,
                _registered_method=True)
        self.GetAnomalies = channel.unary_unary(
                '/activity.ActivityGrpcService/GetAnomalies',
                request_serializer=activity__pb2.GetAnomaliesRequest.SerializeToString,
                response_deserializer=activity__pb2.GetAnomaliesReply.FromString,
                _registered_method=True)
        self.DeleteActivity = channel.unary_unary(
                '/activity.ActivityGrpcService/DeleteActivity',
                request_serializer=activity__pb2.DeleteActivityRequest.SerializeToString,
                response_deserializer=activity__pb2.DeleteActivityReply.FromString,
                _registered_method=True)
        self.UpdateActivity = channel.unary_unary(
                '/activity.ActivityGrpcService/UpdateActivity',
                request_serializer=activity__pb2.UpdateActivityRequest.SerializeToString,
                response_deserializer=activity__pb2.ActivityReply.FromString,
                _registered_method=True)
        self.GetActivityStatistics = channel.unary_unary(
                '/activity.ActivityGrpcService/GetActivityStatistics',
                request_serializer=activity__pb2.GetActivityStatisticsRequest.SerializeToString,
                response_deserializer=activity__pb2.GetActivityStatisticsReply.FromString,
                _registered_method=True)


class ActivityGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActivities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivityGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivities,
                    request_deserializer=activity__pb2.GetActivitiesRequest.FromString,
                    response_serializer=activity__pb2.GetActivitiesReply.SerializeToString,
            ),
            'CreateActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateActivity,
                    request_deserializer=activity__pb2.CreateActivityRequest.FromString,
                    response_serializer=activity__pb2.ActivityReply.SerializeToString,
            ),
            'GetActivityById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivityById,
                    request_deserializer=activity__pb2.GetActivityByIdRequest.FromString,
                    response_serializer=activity__pb2.ActivityReply.SerializeToString,
            ),
            'GetAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnomalies,
                    request_deserializer=activity__pb2.GetAnomaliesRequest.FromString,
                    response_serializer=activity__pb2.GetAnomaliesReply.SerializeToString,
            ),
            'DeleteActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteActivity,
                    request_deserializer=activity__pb2.DeleteActivityRequest.FromString,
                    response_serializer=activity__pb2.DeleteActivityReply.SerializeToString,
            ),
            'UpdateActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateActivity,
                    request_deserializer=activity__pb2.UpdateActivityRequest.FromString,
                    response_serializer=activity__pb2.ActivityReply.SerializeToString,
            ),
            'GetActivityStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivityStatistics,
                    request_deserializer=activity__pb2.GetActivityStatisticsRequest.FromString,
                    response_serializer=activity__pb2.GetActivityStatisticsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'activity.ActivityGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('activity.ActivityGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActivityGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/GetActivities',
            activity__pb2.GetActivitiesRequest.SerializeToString,
            activity__pb2.GetActivitiesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/CreateActivity',
            activity__pb2.CreateActivityRequest.SerializeToString,
            activity__pb2.ActivityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivityById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/GetActivityById',
            activity__pb2.GetActivityByIdRequest.SerializeToString,
            activity__pb2.ActivityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/GetAnomalies',
            activity__pb2.GetAnomaliesRequest.SerializeToString,
            activity__pb2.GetAnomaliesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/DeleteActivity',
            activity__pb2.DeleteActivityRequest.SerializeToString,
            activity__pb2.DeleteActivityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/UpdateActivity',
            activity__pb2.UpdateActivityRequest.SerializeToString,
            activity__pb2.ActivityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivityStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityGrpcService/GetActivityStatistics',
            activity__pb2.GetActivityStatisticsRequest.SerializeToString,
            activity__pb2.GetActivityStatisticsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
