# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/agent.AgentManagementService/RegisterAgent',
                request_serializer=agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.UpdateAgentStatus = channel.unary_unary(
                '/agent.AgentManagementService/UpdateAgentStatus',
                request_serializer=agent__pb2.UpdateAgentStatusRequest.SerializeToString,
                response_deserializer=agent__pb2.UpdateAgentStatusResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/agent.AgentManagementService/GetAgent',
                request_serializer=agent__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentsByComputer = channel.unary_unary(
                '/agent.AgentManagementService/GetAgentsByComputer',
                request_serializer=agent__pb2.GetAgentsByComputerRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAgentsByComputerResponse.FromString,
                _registered_method=True)
        self.GetAllAgents = channel.unary_unary(
                '/agent.AgentManagementService/GetAllAgents',
                request_serializer=agent__pb2.GetAllAgentsRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAllAgentsResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/agent.AgentManagementService/DeleteAgent',
                request_serializer=agent__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentPolicy = channel.unary_unary(
                '/agent.AgentManagementService/GetAgentPolicy',
                request_serializer=agent__pb2.GetAgentPolicyRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAgentPolicyResponse.FromString,
                _registered_method=True)
        self.UpsertAgentPolicy = channel.unary_unary(
                '/agent.AgentManagementService/UpsertAgentPolicy',
                request_serializer=agent__pb2.UpsertAgentPolicyRequest.SerializeToString,
                response_deserializer=agent__pb2.UpsertAgentPolicyResponse.FromString,
                _registered_method=True)
        self.DeleteAgentPolicy = channel.unary_unary(
                '/agent.AgentManagementService/DeleteAgentPolicy',
                request_serializer=agent__pb2.DeleteAgentPolicyRequest.SerializeToString,
                response_deserializer=agent__pb2.DeleteAgentPolicyResponse.FromString,
                _registered_method=True)
        self.GetAgentPolicyVersions = channel.unary_unary(
                '/agent.AgentManagementService/GetAgentPolicyVersions',
                request_serializer=agent__pb2.GetAgentPolicyVersionsRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAgentPolicyVersionsResponse.FromString,
                _registered_method=True)
        self.RestoreAgentPolicyVersion = channel.unary_unary(
                '/agent.AgentManagementService/RestoreAgentPolicyVersion',
                request_serializer=agent__pb2.RestoreAgentPolicyVersionRequest.SerializeToString,
                response_deserializer=agent__pb2.RestoreAgentPolicyVersionResponse.FromString,
                _registered_method=True)
        self.GetPendingAgentCommands = channel.unary_unary(
                '/agent.AgentManagementService/GetPendingAgentCommands',
                request_serializer=agent__pb2.GetPendingAgentCommandsRequest.SerializeToString,
                response_deserializer=agent__pb2.GetPendingAgentCommandsResponse.FromString,
                _registered_method=True)
        self.GetAgentCommands = channel.unary_unary(
                '/agent.AgentManagementService/GetAgentCommands',
                request_serializer=agent__pb2.GetAgentCommandsRequest.SerializeToString,
                response_deserializer=agent__pb2.GetAgentCommandsResponse.FromString,
                _registered_method=True)
        self.CreateAgentCommand = channel.unary_unary(
                '/agent.AgentManagementService/CreateAgentCommand',
                request_serializer=agent__pb2.CreateAgentCommandRequest.SerializeToString,
                response_deserializer=agent__pb2.CreateAgentCommandResponse.FromString,
                _registered_method=True)
        self.AckAgentCommand = channel.unary_unary(
                '/agent.AgentManagementService/AckAgentCommand',
                request_serializer=agent__pb2.AckAgentCommandRequest.SerializeToString,
                response_deserializer=agent__pb2.AckAgentCommandResponse.FromString,
                _registered_method=True)
        self.CreateSyncBatch = channel.unary_unary(
                '/agent.AgentManagementService/CreateSyncBatch',
                request_serializer=agent__pb2.CreateSyncBatchRequest.SerializeToString,
                response_deserializer=agent__pb2.CreateSyncBatchResponse.FromString,
                _registered_method=True)
        self.UpdateSyncBatch = channel.unary_unary(
                '/agent.AgentManagementService/UpdateSyncBatch',
                request_serializer=agent__pb2.UpdateSyncBatchRequest.SerializeToString,
                response_deserializer=agent__pb2.UpdateSyncBatchResponse.FromString,
                _registered_method=True)
        self.GetSyncBatch = channel.unary_unary(
                '/agent.AgentManagementService/GetSyncBatch',
                request_serializer=agent__pb2.GetSyncBatchRequest.SerializeToString,
                response_deserializer=agent__pb2.GetSyncBatchResponse.FromString,
                _registered_method=True)
        self.GetSyncBatchesByAgent = channel.unary_unary(
                '/agent.AgentManagementService/GetSyncBatchesByAgent',
                request_serializer=agent__pb2.GetSyncBatchesByAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.GetSyncBatchesByAgentResponse.FromString,
                _registered_method=True)
        self.GetPendingSyncBatches = channel.unary_unary(
                '/agent.AgentManagementService/GetPendingSyncBatches',
                request_serializer=agent__pb2.GetPendingSyncBatchesRequest.SerializeToString,
                response_deserializer=agent__pb2.GetPendingSyncBatchesResponse.FromString,
                _registered_method=True)


class AgentManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentsByComputer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertAgentPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgentPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentPolicyVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreAgentPolicyVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingAgentCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgentCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckAgentCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSyncBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSyncBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncBatchesByAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingSyncBatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'UpdateAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentStatus,
                    request_deserializer=agent__pb2.UpdateAgentStatusRequest.FromString,
                    response_serializer=agent__pb2.UpdateAgentStatusResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=agent__pb2.GetAgentRequest.FromString,
                    response_serializer=agent__pb2.GetAgentResponse.SerializeToString,
            ),
            'GetAgentsByComputer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentsByComputer,
                    request_deserializer=agent__pb2.GetAgentsByComputerRequest.FromString,
                    response_serializer=agent__pb2.GetAgentsByComputerResponse.SerializeToString,
            ),
            'GetAllAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllAgents,
                    request_deserializer=agent__pb2.GetAllAgentsRequest.FromString,
                    response_serializer=agent__pb2.GetAllAgentsResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=agent__pb2.DeleteAgentRequest.FromString,
                    response_serializer=agent__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'GetAgentPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentPolicy,
                    request_deserializer=agent__pb2.GetAgentPolicyRequest.FromString,
                    response_serializer=agent__pb2.GetAgentPolicyResponse.SerializeToString,
            ),
            'UpsertAgentPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertAgentPolicy,
                    request_deserializer=agent__pb2.UpsertAgentPolicyRequest.FromString,
                    response_serializer=agent__pb2.UpsertAgentPolicyResponse.SerializeToString,
            ),
            'DeleteAgentPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgentPolicy,
                    request_deserializer=agent__pb2.DeleteAgentPolicyRequest.FromString,
                    response_serializer=agent__pb2.DeleteAgentPolicyResponse.SerializeToString,
            ),
            'GetAgentPolicyVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentPolicyVersions,
                    request_deserializer=agent__pb2.GetAgentPolicyVersionsRequest.FromString,
                    response_serializer=agent__pb2.GetAgentPolicyVersionsResponse.SerializeToString,
            ),
            'RestoreAgentPolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreAgentPolicyVersion,
                    request_deserializer=agent__pb2.RestoreAgentPolicyVersionRequest.FromString,
                    response_serializer=agent__pb2.RestoreAgentPolicyVersionResponse.SerializeToString,
            ),
            'GetPendingAgentCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingAgentCommands,
                    request_deserializer=agent__pb2.GetPendingAgentCommandsRequest.FromString,
                    response_serializer=agent__pb2.GetPendingAgentCommandsResponse.SerializeToString,
            ),
            'GetAgentCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentCommands,
                    request_deserializer=agent__pb2.GetAgentCommandsRequest.FromString,
                    response_serializer=agent__pb2.GetAgentCommandsResponse.SerializeToString,
            ),
            'CreateAgentCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgentCommand,
                    request_deserializer=agent__pb2.CreateAgentCommandRequest.FromString,
                    response_serializer=agent__pb2.CreateAgentCommandResponse.SerializeToString,
            ),
            'AckAgentCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.AckAgentCommand,
                    request_deserializer=agent__pb2.AckAgentCommandRequest.FromString,
                    response_serializer=agent__pb2.AckAgentCommandResponse.SerializeToString,
            ),
            'CreateSyncBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSyncBatch,
                    request_deserializer=agent__pb2.CreateSyncBatchRequest.FromString,
                    response_serializer=agent__pb2.CreateSyncBatchResponse.SerializeToString,
            ),
            'UpdateSyncBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSyncBatch,
                    request_deserializer=agent__pb2.UpdateSyncBatchRequest.FromString,
                    response_serializer=agent__pb2.UpdateSyncBatchResponse.SerializeToString,
            ),
            'GetSyncBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncBatch,
                    request_deserializer=agent__pb2.GetSyncBatchRequest.FromString,
                    response_serializer=agent__pb2.GetSyncBatchResponse.SerializeToString,
            ),
            'GetSyncBatchesByAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncBatchesByAgent,
                    request_deserializer=agent__pb2.GetSyncBatchesByAgentRequest.FromString,
                    response_serializer=agent__pb2.GetSyncBatchesByAgentResponse.SerializeToString,
            ),
            'GetPendingSyncBatches': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingSyncBatches,
                    request_deserializer=agent__pb2.GetPendingSyncBatchesRequest.FromString,
                    response_serializer=agent__pb2.GetPendingSyncBatchesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/RegisterAgent',
            agent__pb2.RegisterAgentRequest.SerializeToString,
            agent__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/UpdateAgentStatus',
            agent__pb2.UpdateAgentStatusRequest.SerializeToString,
            agent__pb2.UpdateAgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAgent',
            agent__pb2.GetAgentRequest.SerializeToString,
            agent__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentsByComputer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAgentsByComputer',
            agent__pb2.GetAgentsByComputerRequest.SerializeToString,
            agent__pb2.GetAgentsByComputerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAllAgents',
            agent__pb2.GetAllAgentsRequest.SerializeToString,
            agent__pb2.GetAllAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/DeleteAgent',
            agent__pb2.DeleteAgentRequest.SerializeToString,
            agent__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAgentPolicy',
            agent__pb2.GetAgentPolicyRequest.SerializeToString,
            agent__pb2.GetAgentPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertAgentPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/UpsertAgentPolicy',
            agent__pb2.UpsertAgentPolicyRequest.SerializeToString,
            agent__pb2.UpsertAgentPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgentPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/DeleteAgentPolicy',
            agent__pb2.DeleteAgentPolicyRequest.SerializeToString,
            agent__pb2.DeleteAgentPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentPolicyVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAgentPolicyVersions',
            agent__pb2.GetAgentPolicyVersionsRequest.SerializeToString,
            agent__pb2.GetAgentPolicyVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreAgentPolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/RestoreAgentPolicyVersion',
            agent__pb2.RestoreAgentPolicyVersionRequest.SerializeToString,
            agent__pb2.RestoreAgentPolicyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingAgentCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetPendingAgentCommands',
            agent__pb2.GetPendingAgentCommandsRequest.SerializeToString,
            agent__pb2.GetPendingAgentCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetAgentCommands',
            agent__pb2.GetAgentCommandsRequest.SerializeToString,
            agent__pb2.GetAgentCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgentCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/CreateAgentCommand',
            agent__pb2.CreateAgentCommandRequest.SerializeToString,
            agent__pb2.CreateAgentCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckAgentCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/AckAgentCommand',
            agent__pb2.AckAgentCommandRequest.SerializeToString,
            agent__pb2.AckAgentCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSyncBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/CreateSyncBatch',
            agent__pb2.CreateSyncBatchRequest.SerializeToString,
            agent__pb2.CreateSyncBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSyncBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/UpdateSyncBatch',
            agent__pb2.UpdateSyncBatchRequest.SerializeToString,
            agent__pb2.UpdateSyncBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetSyncBatch',
            agent__pb2.GetSyncBatchRequest.SerializeToString,
            agent__pb2.GetSyncBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncBatchesByAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetSyncBatchesByAgent',
            agent__pb2.GetSyncBatchesByAgentRequest.SerializeToString,
            agent__pb2.GetSyncBatchesByAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingSyncBatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentManagementService/GetPendingSyncBatches',
            agent__pb2.GetPendingSyncBatchesRequest.SerializeToString,
            agent__pb2.GetPendingSyncBatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
