# .dockerignore: bin/, obj/, *.log, .git/, node_modules/
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
ARG TARGETARCH

WORKDIR /src
COPY ["ActivityService.csproj", "."]
RUN dotnet restore "ActivityService.csproj" \
    --runtime linux-x64 --runtime linux-arm64 \
    --disable-parallel

COPY . .
RUN dotnet publish "ActivityService.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    /p:UseAppHost=false \
    --no-restore \
    /p:PublishReadyToRun=true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true \
    /p:SelfContained=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
ARG TARGETARCH

WORKDIR /app
EXPOSE 5001 5002

# ENV для prod
ENV ASPNETCORE_URLS=http://+:5001;http://+:5002
ENV DOTNET_EnableDiagnostics=0
ENV DOTNET_GCName=coreclr
ENV DOTNET_gcServer=0

COPY --from=build /app/publish .

# User non-root
RUN addgroup --system --gid 1000 aspnet && \
    adduser --system --uid 1000 --gid 1000 --shell /bin/sh aspnet && \
    chown -R aspnet:aspnet /app
USER aspnet

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:5002/health || exit 1

ENTRYPOINT ["./ActivityService"]
