ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS health_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS queue_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS last_collected_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS last_sent_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS last_error VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS policy_version VARCHAR(50) NULL;
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS capabilities_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS collector_statuses_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE IF EXISTS agents ADD COLUMN IF NOT EXISTS source_platform VARCHAR(50) NULL;
