ALTER TABLE IF EXISTS agent_policies ADD COLUMN IF NOT EXISTS enable_whitelist BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS agent_policies ADD COLUMN IF NOT EXISTS enable_blacklist BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS agent_policies ADD COLUMN IF NOT EXISTS whitelist_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE IF EXISTS agent_policies ADD COLUMN IF NOT EXISTS blacklist_json TEXT NOT NULL DEFAULT '[]';
